# Generated by Django 4.2.30 on 2026-07-14 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='directoryitem',
            unique_together={('user', 'type', 'name')},
        ),
    ]
