# Generated by Django 4.2.30 on 2026-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Целевая сумма')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Текущая сумма')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Фонд',
                'verbose_name_plural': 'Фонды',
                'ordering': ['-created_at'],
            },
        ),
    ]
