# Generated by Django 4.2.30 on 2026-07-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('fund', 'Пополнение фонда')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторяющийся')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('directory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='directories.directoryitem', verbose_name='Статья')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='funds.fund', verbose_name='Фонд')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
